# file: nginx/tasks/modules/ngx_pagespeed.yml
# configure flag: --add-module=/tmp/ngx_pagespeed-release-{{nginx_ngx_pagespeed_version}}-beta

- name: Nginx | Modules | Make sure the dependences are installed
  apt:
    pkg: "{{item}}"
  with_items:
    - libpcre3
    - libpcre3-dev
    - uuid-dev

- name: Nginx | Modules | Download the ngx_pagespeed source
  get_url:
    url: "https://github.com/apache/incubator-pagespeed-ngx/archive/v{{nginx_ngx_pagespeed_version}}-stable.tar.gz"
    dest: "/tmp/ngx_pagespeed_module.tar.gz"

- name: Nginx | Modules | Unpack the ngx_pagespeed source
  unarchive:
    remote_src: yes
    src: /tmp/ngx_pagespeed_module.tar.gz
    dest: /tmp

- name: Nginx | Modules | Place install-script for pagespeed and psol
  template:
    src: ./modules/pagespeed_install.j2
    dest: "/tmp/installPagespeed.sh"

- name: Nginx | Modules | Making install-script executable
  file: dest=/tmp/installPagespeed.sh mode=a+x

- name: Nginx | Modules | Run Pagespeed and Psol install-script
  command: bash /tmp/installPagespeed.sh

- set_fact:
    nginx_modules_pagespeed: true
    cacheable: true