# file: nginx/tasks/commons.yml

- name: Nginx | Make sure the nginx directory exists
  file:
    path: "{{nginx_dir}}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Nginx | Make sure the nginx log directory exists
  file:
    path: "{{nginx_log_dir}}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Nginx | Make sure the sites-available, sites-enabled, modules and conf.d directories exist
  file:
    path: "{{nginx_dir}}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: ["sites-available", "sites-enabled", "conf.d", "modules", "naxsi"]

- name: Nginx | Make sure the temp folders exist
  file:
    path: "{{item}}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755
    state: directory
  with_items: ["{{http_client_body_temp_path}}", "{{http_proxy_temp_path}}", "{{http_fastcgi_temp_path}}"]

